export const DEFAULT_TIMER_DISPLAY_STRING = "00:00:00";
export const CY_SELECTOR_VAL_TIMER_DISPLAY_INPUT = "cy-timer-display-input";
export const CY_SELECTOR_VAL_TIMER_DISPLAY_WRAPPER = "cy-timer-display";
export const CY_SELECTOR_TIMER_DISPLAY_WRAPPER = `[data-cy="${CY_SELECTOR_VAL_TIMER_DISPLAY_WRAPPER}"]`;
export const CY_SELECTOR_TIMER_DISPLAY_INPUT = `[data-cy="${CY_SELECTOR_VAL_TIMER_DISPLAY_INPUT}"]`;

// 120.5 Minutes
export const MOCK_TIMER_DISPLAY_EXPECTED_FORMATTED_TEXT = '02:00:30';
